export const PROJECT_STATUS = {
  ACTIVE: 'active',
  STAGNANT: 'stagnant',
  ARCHIVED: 'archived',
  MVP_SHIPPED: 'mvp_shipped'
};

export const ALLOWED_STATUS_TRANSITIONS = {
  [PROJECT_STATUS.ACTIVE]: [PROJECT_STATUS.STAGNANT, PROJECT_STATUS.ARCHIVED, PROJECT_STATUS.MVP_SHIPPED],
  [PROJECT_STATUS.STAGNANT]: [PROJECT_STATUS.ACTIVE, PROJECT_STATUS.ARCHIVED, PROJECT_STATUS.MVP_SHIPPED],
  [PROJECT_STATUS.ARCHIVED]: [],
  [PROJECT_STATUS.MVP_SHIPPED]: [PROJECT_STATUS.ARCHIVED]
};
